server:
  port: 8001
spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: core-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: 'true'
  datasource:
    password: postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
cloud:
  aws:
    region:
      static: us-west-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key:
      secret-key:
    end-point:
      uri: "https://sqs.us-west-2.amazonaws.com/895656015678/unsplash-upload-queue"
