apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubesecrets.yml
  - postgresql.yml
  - postgresql-service.yml
  - unsplash-eureka.yml
  - unsplash-eureka-service.yml
  - unsplash-core.yml
  - unsplash-core-service.yml
  - unsplash-upload.yml
  - unsplash-upload-service.yml
  - unsplash-comment.yml
  - unsplash-comment-service.yml
  - unsplash-auth.yml
  - unsplash-auth-service.yml
