---
apiVersion: v1
kind: Service
metadata:
  name: unsplash-comment-service
spec:
  type: ClusterIP
  selector:
    app: unsplash-comment
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
