---
apiVersion: v1
kind: Service
metadata:
  name: unsplash-eureka-service
spec:
  type: ClusterIP
  selector:
    app: unsplash-eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
