---
apiVersion: v1
kind: Service
metadata:
  name: unsplash-upload-service
spec:
  type: ClusterIP
  selector:
    app: unsplash-upload
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
