---
apiVersion: v1
kind: Service
metadata:
  name: unsplash-auth-service
spec:
  type: LoadBalancer
  selector:
    app: unsplash-auth
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
