---
apiVersion: v1
kind: Service
metadata:
  name: unsplash-core-service
spec:
  type: ClusterIP
  selector:
    app: unsplash-core
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
