version: '2'

services:
  app:
    image: 'unsplash-app'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/vishnu
      - DB_USER=vishnu
      - DB_PWD=vishnu123

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=vishnu
      - POSTGRES_PASSWORD=vishnu123
      - POSTGRES_DB=vishnu