---

apiVersion: v1
kind: Service
metadata:
  name: unsplash-postgres
  labels:
    db: unsplash-postgres
spec:
  type: ClusterIP
  selector:
    db: unsplash-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432